language: ruby
rvm:
- 2.7.1
install:
  - bundle install
  - nvm install 10
  - npm i -g yarn
  - yarn
services:
  - postgresql
script:
  - bundle exec rake db:migrate:reset RAILS_ENV=test
  - bundle exec rspec
  - git fetch origin master && master_sha1="$(cut -c -40<<<"$(cat .git/FETCH_HEAD)")" && pronto run -c $master_sha1 --exit-code
